#+title: bootstrap.org
#+author: Luis Henriquez-Perez
#+property: header-args :tangle no
#+tags: bootstrap dotfiles

The purpose of this file is to boostrap my Emacs config. More specifically, it's
the file that's evaluated that contains the instructions for how to bootstrap my
Emacs config.

* about
:PROPERTIES:
:ID:       c33e5124-fbc8-4d54-8b10-1f33ffbdd64f
:END:

To bootstrap my dotfiles run ~emacs --script bootstrap.sh~.

* load org-mode
:PROPERTIES:
:ID:       c82d1f3f-ac39-492d-b7c8-b1bb7f6b80c7
:END:

#+begin_src emacs-lisp
(require 'org)
#+end_src

* load the library of babel
:PROPERTIES:
:ID:       f6238cb4-9b85-49ef-baf3-eb63e7dbc0c5
:END:

The library of babel is what contains extensions that I've written to org-mode
as well as things that are better done during tangling (for performance reasons)
such as.

#+begin_src emacs-lisp
(require 'ob-lob)
(org-babel-lob-ingest "library-of-babel.org")
#+end_src

* install packages
:PROPERTIES:
:ID:       e4ff6228-2533-45f0-bf96-be137efcb4b9
:END:

#+begin_src emacs-lisp
(defun xl-bootstrap:install-packages ()
  "Install packages based on the recipe file."
  )
#+end_src

* tangle emacs
:PROPERTIES:
:ID:       6bfe2d01-e068-4650-9f3e-4e4ddfc2f4a6
:END:

I conservatively just tangle the Emacs stuff and leave it to myself to do the
rest in an Emacs session. As I accrue more knowledge on bootstrapping I'll
change this so that I can provide myself options for what I want to do. For this
I need to research how to prompt in the shell.

#+begin_src emacs-lisp
(org-babel-tangle "")

(cl-find (lambda (str) (s-match (rx "boostrap.sh") str)) nowed)
(let ((tangle-dir (expand-file-name))
      (tan))
  ;; (print (format "I did it. you passed in %s" command-line-args-left))
  (print "Loading the library of babel from %s...")
  (org-babel-lob-ingest "library-of-babel.org")
  ;; find the command-line arg that contains the path to this file.
  ;; then tangle the emacs.org file relative to that
  (print "Tangling recipes...")
  (org-babel-tangle-file "recipes.org")
  (print "Tangling emacs config...")
  (org-babel-tangle-file "emacs.org")
  (print "Done."))
#+end_src

* main function
:PROPERTIES:
:ID:       93236548-1044-4c66-a998-3e68aee23131
:END:

This function is called when.

#+begin_src emacs-lisp
(defun main ()
  "Do the right thing based on the command line args."
  (bootstrap:build-emacs)
  )
#+end_src

