#+title: README.org
#+author: Luis Henriquez-Perez
#+tags: doc

* Feature List
:PROPERTIES:
:ID:       a3a571ce-0abf-437b-b5bf-d95b4464fcfb
:END:

* org-mode
:PROPERTIES:
:ID:       45c846bf-5cbc-4437-af99-d9ec3b42cc2d
:END:

This headline explains why I use [[][org-mode] as the centerpiece of my configuration.

** divide and conquer
:PROPERTIES:
:ID:       a28eda39-f3e5-4e73-a380-4f44d27d9a07
:END:

One of big goals for my dotfile design is to allow me to "divide and conquer"
problems more easily.

** homogenous throughout dotfiles
:PROPERTIES:
:ID:       b4906e21-20fd-4bb4-9f2f-e6e745d0b41e
:END:

One of the great strengths of using org-mode for all my dotfiles is the
consistency and homogenuity it provides. Typically dotfiles are in several
different languges. And documentation, in turn, is done via comments in several
different syntaxes. Most programming languages don't allow markup in their
comments and don't allow linking to other files or websites. Thus, we're left
with a mess. Instead, with org-mode I can document all my dotfiles the same way.
All of them will have the same general structure, so it is very predictable and
easy to follow.

** documentation based
:PROPERTIES:
:ID:       05a0ce02-8dbf-4e4a-9c45-2ce857fe4a2a
:END:

Org files lend themselves well to documentation. As I mentioned Org is a markup
language. It provides a syntax for links and a syntax for referencing other
files.

** powerful searching via tags
:PROPERTIES:
:ID:       7e0a68ef-5f9c-4017-97f2-2ea3454421e3
:END:

I use tags heavily in my dotfiles. Each headline should have at least one tag.

** flexible directory structure
:PROPERTIES:
:ID:       ff12f1ee-7c36-4385-9b67-eefbebc4c54d
:END:

Since I can specify where I want my org files tangled.

** hackable and minimal
:PROPERTIES:
:ID:       bea7b6a6-e24a-41a4-9637-149c5f986685
:END:

* Design Choices
:PROPERTIES:
:ID:       9f67931c-d9c6-4f6d-8a07-eab363d3d6bf
:END:

** org-mode
:PROPERTIES:
:ID:       976c09e0-1c90-4a4b-8779-ce79f2c69794
:END:
:LINKS:
https://irreal.org/blog/?p=2559
http://sleepomeno.github.io/blog/2014/02/16/This-is-not-an-org-mode-Tutorial/
:END:

I write my dotfiles in org-mode and tangle them to their corronding places with [[][org-mode].
Org mode allows me to express my dotfiles in a homogenous syntax.

Org allows me to have expressive documentation.

** tag-based
:PROPERTIES:
:ID:       9c7e9022-4dec-4299-a487-ea16000fb5ec
:END:

** prefer level-1 directory structure
:PROPERTIES:
:ID:       90e53ab7-9073-49c7-9105-3d949753abfb
:END:

I have never liked complex directory structures (or even complex file structures
for that matter). It make is more diffult for me to traverse and more error
prone because I need to remember what is in which directory. I also don't want
others looking at my dotfiles to have to guess where stuff is. That's why I'd
like to keep the directory hierarchy as minimal and simple as possible.

As I mentioned, I'd ideally prefer a tag-based structure and, indeed, I have
used tags throughout my org files so that my dotfiles can be used in this way.
But I cannot ignore the fact that.

* How it Works
:PROPERTIES:
:ID:       00e2ab6a-254a-4bf7-b44b-44555243d1cd
:END:

** Bootstrap
:PROPERTIES:
:ID:       a73952cd-104f-4ccf-9e20-2252ef13442d
:END:

To bootstrap my config run the [[][bootstrap.sh] script. It's a script that
will. Note that this script assumes Emacs is already installed.

#+begin_src shell
sh bootstraph.sh
#+end_src

** Setting Up Dotfiles
:PROPERTIES:
:ID:       5bb7ca90-711d-44ea-9272-cd8736ee9a2a
:END:

My dotfiles are written as org-mode files. Each When I make a change to an org-mode
file and want its target. Whenever I change a configuration file, I need to
[[][tangle] it so that the changes are written to the file itself.

#+begin_src emacs-lisp
#+end_src

** Library of Babel
:PROPERTIES:
:ID:       c495a9f3-8054-4045-af36-267406a4bc4a
:END:

The library of babel is where I put code I want to work on my config as a whole.

* Goals
:PROPERTIES:
:ID:       28970211-6d6f-455c-9b07-9e0f5d3c5ba3
:END:

** Reproducability
:PROPERTIES:
:ID:       c5afe78f-bbb4-4810-b259-b21e8e8c3cea
:END:

Just like in every dotfile system, the main purpose is to reproduce a computer
setup onto a given machine. So if your computer ever crashes or is destroyed, or
even if you just don't have access to your computer you can get a full, working
setup on any computer.

** Consistency
:PROPERTIES:
:ID:       c6b64409-53eb-43da-a859-9897d29f7d5b
:END:

By consistency I mean being able to write configuration files in one language.
All my configuration files are written in org mode. Making their strucutre, the
same.

** Documentation
:PROPERTIES:
:ID:       6de0bc56-af6f-4981-bda5-26655c92e93b
:END:

Documentation is very important for me; and, its partly why I'm using org mode.
Org Mode is a featureful markup language that lets me document my thoughts in a
way that's not possible with just docstrings and comments.

*** web page screenshots :webshot:
:PROPERTIES:
:ID:       8d3fabcd-0180-46f7-93f2-911c3b3a80f8
:END:
:LINKS:
https://github.com/Y2Z/monolith
:END:

Saving links is good, but it is not enough. Websites can be (and are often)
modified. They can be taken down in which case any links would them would either
break or point to someplace else. A true data hoarder saves webpages they deem
useful on their computer.

**** monolith :webshot:
:PROPERTIES:
:ID:       9ecae28c-1741-4aad-9c5b-646045e714d3
:END:

[[https://github.com/Y2Z/monolith][monolith]] is a program meant to

#+begin_src shell
monolith https://github.com/Y2Z/monolith -o ~/.tangld/src/multimedia/webshots/monolith-github-page.html
#+end_src

* Screenshots
:PROPERTIES:
:ID:       878de7ed-1230-4466-8f37-ba55dcaeac19
:END:
