#+title: README.org
#+author: Luis Henriquez-Perez
#+tags: doc

* Design Choices
:PROPERTIES:
:ID:       9f67931c-d9c6-4f6d-8a07-eab363d3d6bf
:END:

** org-mode
:PROPERTIES:
:ID:       976c09e0-1c90-4a4b-8779-ce79f2c69794
:END:
:LINKS:
https://irreal.org/blog/?p=2559
http://sleepomeno.github.io/blog/2014/02/16/This-is-not-an-org-mode-Tutorial/
:END:

I write my dotfiles in org-mode and tangle them to their corronding places with
[[][tangld]. Org mode allows me to express my dotfiles in a homogenous syntax.

Org allows me to have expressive documentation.

** tangld
:PROPERTIES:
:ID:       497747db-7e2e-4548-bc88-2bd37328d6eb
:END:

[[][tangld] is what I use to

#+begin_src emacs-lisp
#+end_src

** tag-based
:PROPERTIES:
:ID:       9c7e9022-4dec-4299-a487-ea16000fb5ec
:END:

* How it Works
:PROPERTIES:
:ID:       00e2ab6a-254a-4bf7-b44b-44555243d1cd
:END:

** Bootstrap
:PROPERTIES:
:ID:       a73952cd-104f-4ccf-9e20-2252ef13442d
:END:

To bootstrap my config run the [[][bootstrap.sh] script. It's a script that
will. Note that this script assumes Emacs is already installed.

#+begin_src shell
sh bootstraph.sh
#+end_src

** Setting Up Dotfiles
:PROPERTIES:
:ID:       5bb7ca90-711d-44ea-9272-cd8736ee9a2a
:END:

Whenever I change a configuration file, I need to [[][tangle] it so that the
changes are written to the file itself.

#+begin_src emacs-lisp
#+end_src

** Library of Babel
:PROPERTIES:
:ID:       c495a9f3-8054-4045-af36-267406a4bc4a
:END:

* Goals
:PROPERTIES:
:ID:       28970211-6d6f-455c-9b07-9e0f5d3c5ba3
:END:

** Reproducability
:PROPERTIES:
:ID:       c5afe78f-bbb4-4810-b259-b21e8e8c3cea
:END:

Just like in every dotfile system, the main purpose is to reproduce a computer
setup onto a given machine. So if your computer ever crashes or is destroyed, or
even if you just don't have access to your computer you can get a full, working
setup on any computer.

** Consistency
:PROPERTIES:
:ID:       c6b64409-53eb-43da-a859-9897d29f7d5b
:END:

By consistency I mean being able to write configuration files in one language.
All my configuration files are written in org mode. Making their strucutre, the
same.

** Documentation
:PROPERTIES:
:ID:       6de0bc56-af6f-4981-bda5-26655c92e93b
:END:

Documentation is very important for me; and, its partly why I'm using org mode.
Org Mode is a featureful markup language that lets me document my thoughts in a
way that's not possible with just docstrings and comments.

*** web page screenshots :webshot:
:PROPERTIES:
:ID:       8d3fabcd-0180-46f7-93f2-911c3b3a80f8
:END:
:LINKS:
https://github.com/Y2Z/monolith
:END:

Saving links is good, but it is not enough. Websites can be (and are often)
modified. They can be taken down in which case any links would them would either
break or point to someplace else. A true data hoarder saves webpages they deem
useful on their computer.

**** monolith :webshot:
:PROPERTIES:
:ID:       9ecae28c-1741-4aad-9c5b-646045e714d3
:END:

[[https://github.com/Y2Z/monolith][monolith]] is a program meant to

#+begin_src shell
monolith https://github.com/Y2Z/monolith -o ~/.tangld/src/multimedia/webshots/monolith-github-page.html
#+end_src

* Screenshots
:PROPERTIES:
:ID:       878de7ed-1230-4466-8f37-ba55dcaeac19
:END:
